"""Sampling-method-independent Monte Carlo and MLMC machinery.

The classes in this module do not know whether a conductivity realization
was generated by a Karhunen--Loeve expansion, an SPDE, or another method.
They require only a sampler that returns the coupled conductivities needed
for one correction

    Y_0 = Q_0,
    Y_l = Q_l - Q_(l-1),  l > 0.
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from typing import Protocol

import ngsolve as ng
import numpy as np


class QoILevel(Protocol):
    """Minimal interface required from one deterministic PDE level."""

    level_index: int

    def solve_qoi(
        self,
        kappa: ng.CoefficientFunction,
    ) -> float:
        """Solve with ``kappa`` and return the quantity of interest."""
        ...


class MCLevelFactoryProtocol(Protocol):
    """Construct a new, independently mutable solver for ``Q_l``."""

    def __call__(self, level_index: int) -> QoILevel:
        ...


@dataclass(frozen=True)
class CoupledConductivitySample:
    """Conductivity input or coupled pair required for one MLMC sample.

    ``upper`` is used to compute ``Q_l``. For ``l > 0``, ``lower`` is the
    coupled realization used to compute ``Q_(l-1)``. A KL sampler normally
    places the same coordinate-based coefficient in both entries. An SPDE
    sampler may return two mesh-dependent approximations generated from one
    hierarchically coupled white-noise realization.
    """

    upper: ng.CoefficientFunction
    lower: ng.CoefficientFunction | None


class CoupledConductivitySampler(Protocol):
    """Generate the random coefficient input for one correction sample."""

    def draw(
        self,
        rng: np.random.Generator,
    ) -> CoupledConductivitySample:
        ...


class CoupledSamplerFactory(Protocol):
    """Build a private random-field sampler for one MLMC term."""

    def __call__(
        self,
        *,
        level_index: int,
        upper_level: QoILevel,
        lower_level: QoILevel | None,
    ) -> CoupledConductivitySampler:
        ...


@dataclass
class RunningStatistics:
    """Store samples and update their mean and variance incrementally.

    ``sum_squared_deviations`` is Welford's running quantity

        M2 = sum_i (value_i - sample_mean)**2.

    It avoids recomputing the mean and variance from the complete sample
    list after every new value. The values are still retained for plotting
    and distribution diagnostics.
    """

    count: int = 0
    mean: float = 0.0
    sum_squared_deviations: float = 0.0
    values: list[float] = field(default_factory=list)

    def update(self, value: float) -> None:
        """Add one finite sample using Welford's stable recurrence."""
        value = float(value)
        if not np.isfinite(value):
            raise ValueError("A running-statistics sample must be finite.")

        self.values.append(value)
        self.count += 1

        difference = value - self.mean
        self.mean += difference / self.count
        difference_from_new_mean = value - self.mean
        self.sum_squared_deviations += (
            difference * difference_from_new_mean
        )

    @property
    def sample_variance(self) -> float:
        """Unbiased variance of individual samples."""
        if self.count < 2:
            return float("inf")
        return self.sum_squared_deviations / (self.count - 1)

    @property
    def variance_of_mean(self) -> float:
        """Estimated sampling variance of the sample mean."""
        if self.count < 2:
            return float("inf")
        return self.sample_variance / self.count


@dataclass
class MLMCTerm:
    """One independently sampled correction ``Y_l``.

    The upper and lower PDE solvers and the conductivity sampler are private
    to this term. This makes different terms safe to execute concurrently,
    provided each term is run by only one worker at a time.
    """

    level_index: int
    upper_level: QoILevel
    lower_level: QoILevel | None
    conductivity_sampler: CoupledConductivitySampler
    rng: np.random.Generator
    statistics: RunningStatistics = field(default_factory=RunningStatistics)
    upper_qois: list[float] = field(default_factory=list)
    lower_qois: list[float] = field(default_factory=list)
    sample_durations_seconds: list[float] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.level_index < 0:
            raise ValueError("level_index must be nonnegative.")
        if self.upper_level.level_index != self.level_index:
            raise ValueError("upper_level has the wrong level index.")

        if self.level_index == 0:
            if self.lower_level is not None:
                raise ValueError("Y_0 must not have a lower level.")
        elif (
            self.lower_level is None
            or self.lower_level.level_index != self.level_index - 1
        ):
            raise ValueError("Y_l requires a Q_(l-1) lower level.")

    def draw_sample(self) -> float:
        """Generate, solve, and store one sample of ``Y_l``."""
        sample_started = time.perf_counter()
        conductivities = self.conductivity_sampler.draw(self.rng)

        if self.level_index == 0:
            if conductivities.lower is not None:
                raise RuntimeError(
                    "The Y_0 sampler must not return a lower conductivity."
                )
            q_lower = None
            q_upper = self.upper_level.solve_qoi(conductivities.upper)
        else:
            if self.lower_level is None or conductivities.lower is None:
                raise RuntimeError(
                    "A correction sample requires a coupled lower input."
                )
            q_lower = self.lower_level.solve_qoi(conductivities.lower)
            q_upper = self.upper_level.solve_qoi(conductivities.upper)

        correction = self.update_statistics(
            q_upper=q_upper,
            q_lower=q_lower,
        )
        self.sample_durations_seconds.append(
            time.perf_counter() - sample_started
        )
        return correction

    def update_statistics(
        self,
        *,
        q_upper: float,
        q_lower: float | None,
    ) -> float:
        """Store the component QoIs and update statistics for ``Y_l``."""
        q_upper = float(q_upper)
        if not np.isfinite(q_upper):
            raise RuntimeError(
                f"Y_{self.level_index} received a nonfinite upper QoI."
            )

        if self.level_index == 0:
            if q_lower is not None:
                raise ValueError("Y_0 must not receive q_lower.")
            correction = q_upper
        else:
            if q_lower is None:
                raise ValueError("A correction term requires q_lower.")
            q_lower = float(q_lower)
            if not np.isfinite(q_lower):
                raise RuntimeError(
                    f"Y_{self.level_index} received a nonfinite lower QoI."
                )
            correction = q_upper - q_lower

        if not np.isfinite(correction):
            raise RuntimeError(
                f"Y_{self.level_index} produced a nonfinite correction."
            )

        self.upper_qois.append(q_upper)
        if q_lower is not None:
            self.lower_qois.append(q_lower)
        self.statistics.update(correction)
        return correction

    def add_samples(self, number_of_samples: int) -> None:
        """Draw a requested number of additional samples."""
        if number_of_samples < 0:
            raise ValueError("number_of_samples must be nonnegative.")
        for _ in range(number_of_samples):
            self.draw_sample()

    def run_to_mean_variance_target(
        self,
        target_variance: float,
        *,
        minimum_samples: int = 10,
        maximum_samples: int = 100_000,
        samples_per_iteration: int = 1,
        verbose: bool = False,
    ) -> bool:
        """Sample until ``sample_variance(Y_l) / N_l`` reaches a target."""
        if not np.isfinite(target_variance) or target_variance <= 0.0:
            raise ValueError("target_variance must be finite and positive.")
        if minimum_samples < 2:
            raise ValueError("minimum_samples must be at least 2.")
        if maximum_samples < minimum_samples:
            raise ValueError(
                "maximum_samples must be at least minimum_samples."
            )
        if samples_per_iteration < 1:
            raise ValueError("samples_per_iteration must be positive.")

        if self.sample_count < minimum_samples:
            self.add_samples(minimum_samples - self.sample_count)

        if self.variance_of_mean <= target_variance:
            return True

        maximum_iterations = math.ceil(
            (maximum_samples - self.sample_count) / samples_per_iteration
        )
        for iteration in range(1, maximum_iterations + 1):
            remaining = maximum_samples - self.sample_count
            if remaining <= 0:
                return False

            self.add_samples(min(samples_per_iteration, remaining))

            if verbose:
                print(
                    f"Y_{self.level_index}: iteration={iteration}, "
                    f"N={self.sample_count}, "
                    f"V={self.sample_variance:.3e}, "
                    f"V/N={self.variance_of_mean:.3e}, "
                    f"target={target_variance:.3e}"
                )

            if self.variance_of_mean <= target_variance:
                return True

        return False

    @property
    def sample_count(self) -> int:
        return self.statistics.count

    @property
    def mean(self) -> float:
        return self.statistics.mean

    @property
    def sample_variance(self) -> float:
        return self.statistics.sample_variance

    @property
    def variance_of_mean(self) -> float:
        return self.statistics.variance_of_mean

    @property
    def corrections(self) -> np.ndarray:
        """Return a copy of all stored samples of ``Y_l``."""
        return np.asarray(self.statistics.values, dtype=float)

    @property
    def total_sampling_time_seconds(self) -> float:
        return float(sum(self.sample_durations_seconds))

    @property
    def mean_sample_time_seconds(self) -> float:
        if not self.sample_durations_seconds:
            return float("nan")
        return float(np.mean(self.sample_durations_seconds))


@dataclass
class MultilevelMonteCarlo:
    """Manage the independently sampled MLMC correction terms."""

    terms: tuple[MLMCTerm, ...]

    @classmethod
    def create(
        cls,
        *,
        number_of_levels: int,
        mc_level_factory: MCLevelFactoryProtocol,
        sampler_factory: CoupledSamplerFactory,
        seed: int,
    ) -> "MultilevelMonteCarlo":
        """Build private PDE and random-field state for every term."""
        if number_of_levels < 1:
            raise ValueError("number_of_levels must be positive.")

        child_seeds = np.random.SeedSequence(seed).spawn(number_of_levels)
        terms: list[MLMCTerm] = []

        for level_index in range(number_of_levels):
            upper_level = mc_level_factory(level_index)
            lower_level = (
                None
                if level_index == 0
                else mc_level_factory(level_index - 1)
            )
            sampler = sampler_factory(
                level_index=level_index,
                upper_level=upper_level,
                lower_level=lower_level,
            )
            terms.append(
                MLMCTerm(
                    level_index=level_index,
                    upper_level=upper_level,
                    lower_level=lower_level,
                    conductivity_sampler=sampler,
                    rng=np.random.default_rng(child_seeds[level_index]),
                )
            )

        return cls(terms=tuple(terms))

    def add_samples(
        self,
        level_index: int,
        number_of_samples: int,
    ) -> None:
        """Generate additional samples for one MLMC term."""
        if not 0 <= level_index < len(self.terms):
            raise IndexError(
                f"level_index must be between 0 and {len(self.terms) - 1}."
            )
        self.terms[level_index].add_samples(number_of_samples)

    def run_fixed(self, sample_counts: tuple[int, ...]) -> None:
        """Add ``sample_counts[l]`` samples to every term ``Y_l``."""
        if len(sample_counts) != len(self.terms):
            raise ValueError(
                f"Expected {len(self.terms)} sample counts, "
                f"but received {len(sample_counts)}."
            )
        if any(count < 0 for count in sample_counts):
            raise ValueError("Every sample count must be nonnegative.")

        for level_index, number_of_samples in enumerate(sample_counts):
            self.add_samples(level_index, number_of_samples)

    def run_target_variance(
        self,
        target_variance: float,
        *,
        minimum_samples: int = 10,
        maximum_samples_per_term: int = 100_000,
        samples_per_iteration: int = 1,
        verbose: bool = True,
    ) -> bool:
        """Run until the estimated MLMC sampling variance reaches a target.

        This initial policy divides the total target equally among terms, so
        each term stops when

            Var(Y_l) / N_l <= target_variance / number_of_terms.

        It controls sampling error only; it does not estimate spatial bias.
        """
        if not np.isfinite(target_variance) or target_variance <= 0.0:
            raise ValueError("target_variance must be finite and positive.")

        per_term_target = target_variance / len(self.terms)
        term_results = [
            term.run_to_mean_variance_target(
                target_variance=per_term_target,
                minimum_samples=minimum_samples,
                maximum_samples=maximum_samples_per_term,
                samples_per_iteration=samples_per_iteration,
                verbose=verbose,
            )
            for term in self.terms
        ]
        converged = (
            all(term_results)
            and self.estimator_variance <= target_variance
        )

        if verbose:
            self.print_summary(
                target_variance=target_variance,
                term_results=term_results,
            )
        return converged

    @property
    def estimate_qoi(self) -> float:
        """Current MLMC estimate ``sum_l mean(Y_l)``."""
        missing = [
            term.level_index
            for term in self.terms
            if term.sample_count == 0
        ]
        if missing:
            raise RuntimeError(
                "Every term requires a sample; missing levels "
                f"{missing}."
            )
        return float(sum(term.mean for term in self.terms))

    @property
    def estimator_variance(self) -> float:
        """Estimated variance ``sum_l Var(Y_l)/N_l`` of the estimator."""
        insufficient = [
            term.level_index
            for term in self.terms
            if term.sample_count < 2
        ]
        if insufficient:
            raise RuntimeError(
                "At least two samples per term are required; "
                f"insufficient levels {insufficient}."
            )
        return float(sum(term.variance_of_mean for term in self.terms))

    @property
    def standard_error(self) -> float:
        """Sampling standard deviation of the MLMC estimate."""
        return float(np.sqrt(self.estimator_variance))

    def print_summary(
        self,
        *,
        target_variance: float | None = None,
        term_results: list[bool] | None = None,
    ) -> None:
        """Print counts, variances, and measured costs for all terms."""
        if target_variance is not None and (
            not np.isfinite(target_variance) or target_variance <= 0.0
        ):
            raise ValueError("target_variance must be finite and positive.")
        if term_results is not None and len(term_results) != len(self.terms):
            raise ValueError("term_results has the wrong length.")

        per_term_target = (
            None
            if target_variance is None
            else target_variance / len(self.terms)
        )
        print("MLMC sampling summary")
        for position, term in enumerate(self.terms):
            result = (
                ""
                if term_results is None
                else f", converged={term_results[position]}"
            )
            target = (
                ""
                if per_term_target is None
                else f", target={per_term_target:.3e}"
            )
            print(
                f"Y_{term.level_index}: N={term.sample_count}, "
                f"V={term.sample_variance:.3e}, "
                f"V/N={term.variance_of_mean:.3e}{target}{result}, "
                f"total time={term.total_sampling_time_seconds:.3f}s, "
                f"time/sample={term.mean_sample_time_seconds:.6f}s"
            )

        if all(term.sample_count >= 1 for term in self.terms):
            print(f"MLMC estimate: {self.estimate_qoi:.8e}")
        if all(term.sample_count >= 2 for term in self.terms):
            print(f"Estimator variance: {self.estimator_variance:.8e}")
            print(f"Standard error: {self.standard_error:.8e}")


__all__ = [
    "CoupledConductivitySample",
    "CoupledConductivitySampler",
    "CoupledSamplerFactory",
    "MCLevelFactoryProtocol",
    "MLMCTerm",
    "MultilevelMonteCarlo",
    "QoILevel",
    "RunningStatistics",
]
